driver:
  config:
    driver: freenas-api-nfs
    httpConnection:
      protocol: https
      apiKey: TRUENAS_API_KEY
      host: TRUENAS_HOST
      port: 443
      allowInsecure: true
    zfs:
      datasetParentName: STORAGE_BASE_PATH/volumes
      detachedSnapshotsDatasetParentName: STORAGE_BASE_PATH/snapshots
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: TRUENAS_HOST
      shareAlldirs: false
      shareAllowedHosts: [ ]
      shareAllowedNetworks: [ ]
      shareMaprootUser: root
      shareMaprootGroup: root
      shareMapallUser: ""
      shareMapallGroup: ""

csiDriver:
  name: "org.democratic-csi.freenas-api-nfs"

storageClasses:
  - name: truenas-nfs
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4

controller:
  driver:
    image:
      tag: next

volumeSnapshotClasses:
  - name: truenas
